# Import libries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
# Load the dataset

df = pd.read_csv(r"ridge_regression.csv")

In [4]:
# Head of the dataset 
df.head()

,feature_1,feature_2_mc,feature_3_mc,feature_4,feature_5,feature_6_mc,feature_7,feature_8,noise_1,noise_2,noise_3,noise_4,noise_5,noise_6,noise_7,noise_8,noise_9,noise_10,target
0,67.548412,136.681113,74.904058,11.160537,394.588486,13.926652,-16.522447,0.421922,0.690173,0.130746,-0.231793,-0.007802,0.457751,1.374572,-0.677779,-0.196643,-1.541875,-0.968554,134.043083
1,10.584888,22.233329,10.508898,17.012526,162.191800,28.139002,-16.290166,0.096716,0.782327,-1.113222,0.568251,-1.514520,-2.619945,-0.606891,-0.915810,0.876012,0.664266,-1.219075,-26.813823
2,87.553621,172.345672,94.751066,2.291219,191.159310,3.137131,-10.688365,0.101001,-0.248490,1.399186,-0.635147,0.721966,0.198365,0.762765,1.332185,-0.560118,-0.474221,-0.387968,251.913937
3,75.621412,152.254209,84.322786,49.476168,355.999904,69.945374,13.714077,0.776000,0.033531,0.253237,-0.315592,0.723632,0.580780,2.321409,0.619968,-0.609403,-0.561798,-0.831581,169.374137
4,92.309283,183.101710,101.285729,12.331375,324.547254,18.179052,15.912915,0.399401,0.663990,3.401817,-0.435820,-0.026117,0.460988,0.140603,-1.233827,-1.272347,-0.319837,0.170221,317.867018

In [6]:
# Tail of the 
df.tail()

,feature_1,feature_2_mc,feature_3_mc,feature_4,feature_5,feature_6_mc,feature_7,feature_8,noise_1,noise_2,noise_3,noise_4,noise_5,noise_6,noise_7,noise_8,noise_9,noise_10,target
995,85.933904,168.397963,92.631558,41.669726,278.117956,59.950702,-14.087722,0.861443,1.180555,-0.605156,0.319686,1.735689,1.590589,1.001449,-0.457559,1.093339,0.009035,-1.676065,158.463890
996,51.821150,103.620843,55.285440,33.446798,178.063548,49.890993,9.776528,0.121861,0.073816,1.323277,2.517548,0.165304,-1.916619,-0.398649,0.853120,-0.081948,-0.527589,-0.691923,120.703157
997,20.913632,41.729878,22.685966,2.953540,312.447516,6.905279,14.223410,0.717179,0.859284,0.236330,0.612395,-0.580024,-0.149932,-0.663578,0.830521,0.388768,-0.573233,-1.662678,73.334903
998,54.657041,107.843249,60.379837,45.750630,131.546358,67.311814,3.983354,0.568350,0.189715,0.719818,-1.146777,-1.059161,-0.877698,-0.895878,2.707420,-0.421357,0.577034,-0.889931,80.558724
999,43.004625,88.112896,47.635082,12.315513,360.264609,22.037795,-10.423648,0.487343,0.361479,0.849013,0.331274,-0.322156,-0.249529,0.967376,-0.127555,-0.266029,0.793173,0.888632,76.872214

In [11]:
# check the columns and rows 
print("Number of rows:",df.shape[0])
print("="*100)
print("Number of column:",df.shape[1])

Number of rows: 1000
====================================================================================================
Number of column: 19

In [18]:
# Number of missing  values in whole dataset
missing = df.isna().sum().sum()
print("Number of the missing values in dataset:",missing)
print("="*100)

Number of the missing values in dataset: 0
====================================================================================================

In [22]:
# Check the duplicated rows 
duplicate = df.duplicated().sum()
print("Number of Duplicate rows in dataset:",duplicate)
print("="*100)

Number of Duplicate rows in dataset: 0
====================================================================================================

In [ ]:
# check the columns name 
Col = df.columns.tolist()
i =1
print("Column Names")
for col in Col:
    print(f"{i}) {col}")
    i += 1

1) feature_1
2) feature_2_mc
3) feature_3_mc
4) feature_4
5) feature_5
6) feature_6_mc
7) feature_7
8) feature_8
9) noise_1
10) noise_2
11) noise_3
12) noise_4
13) noise_5
14) noise_6
15) noise_7
16) noise_8
17) noise_9
18) noise_10
19) target

In [27]:
# check the all information of the dataset
print("="*100)
print(df.info())
print("="*100)

====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   feature_1     1000 non-null   float64
 1   feature_2_mc  1000 non-null   float64
 2   feature_3_mc  1000 non-null   float64
 3   feature_4     1000 non-null   float64
 4   feature_5     1000 non-null   float64
 5   feature_6_mc  1000 non-null   float64
 6   feature_7     1000 non-null   float64
 7   feature_8     1000 non-null   float64
 8   noise_1       1000 non-null   float64
 9   noise_2       1000 non-null   float64
 10  noise_3       1000 non-null   float64
 11  noise_4       1000 non-null   float64
 12  noise_5       1000 non-null   float64
 13  noise_6       1000 non-null   float64
 14  noise_7       1000 non-null   float64
 15  noise_8       1000 non-null   float64
 16  noise_9       1000 non-null   float64
 17  noise_10      1000 non-null   float64
 18  target        1000 non-null   float64
dtypes: float64(19)
memory usage: 148.6 KB
None
====================================================================================================